name: Streamlit app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  streamlit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"
      - uses: streamlit/streamlit-app-action@v0.0.3
        with:
          app-path: ui.py
          ruff: true
        env: 
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_SEARCH_KEY: ${{ secrets.AZURE_SEARCH_KEY }}
          AZURE_OPENAI_ENDPOINT: "https://clic-openai.openai.azure.com"
          AZURE_OPENAI_API_VERSION: "2024-02-15-preview"
          AZURE_OPENAI_CHAT_DEPLOYMENT: "gpt4"
          AZURE_OPENAI_EMBEDDING_DEPLOYMENT: "embedding-large"
          AZURE_SEARCH_ENDPOINT: "https://clic-cognitive-search.search.windows.net"
          AZURE_SEARCH_API_VERSION: "2023-07-01-Preview"
          AZURE_SEARCH_INDEX: "clic-index-en-sectioned"
